<a href="https://colab.research.google.com/github/aryaanjalii203/ML-Codes/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install numpy

In [5]:
import numpy as np


In [6]:
lst=[1,2,3,4,5,6]
arr=np.array([1,2,3,4,5,6])
print(lst)
print(arr)
print(type(lst))
print(type(arr))

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
<class 'list'>
<class 'numpy.ndarray'>


In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
matrix=np.zeros((3,4))
print(matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
np.arange(1,12,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [12]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [13]:
b=np.array([[2,3,4],[4,5,6],[7,8,9]])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[2 3 4]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
int64


In [14]:
weights=np.zeros(4)
print(weights)
updated_weights=weights+0.5
print(updated_weights)

[0. 0. 0. 0.]
[0.5 0.5 0.5 0.5]


In [15]:
data=np.array([1,2,3,4,5,6])
reshaped_data=data.reshape(2,3)
print(reshaped_data)
arr1=np.array([10,20,30,40,50,60])
arr2=np.array([20,40,50,60,40,80])
combined_arr=arr1+arr2
print(combined_arr)


[[1 2 3]
 [4 5 6]]
[ 30  60  80 100  90 140]


In [16]:
import numpy as np
data1=np.array([10,20,30])
bias=5
Updated=data1+bias
print(Updated)

[15 25 35]
