<a href="https://colab.research.google.com/github/aryaanjalii203/ML-Codes/blob/main/Pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("student_dataset.csv")

In [5]:
df.head()

,Student_ID,Name,Age,Gender,Math_Score,Science_Score,English_Score,Attendance_Percentage,Passed
0,1,Aarav,15,M,78,82,75,92,True
1,2,Diya,16,F,85,88,80,95,True
2,3,Rahul,15,M,69,70,72,88,True
3,4,Sneha,17,F,90,92,85,98,True
4,5,Karan,16,M,72,75,70,85,True


20 starting rows


In [9]:
df.head(20)

,Student_ID,Name,Age,Gender,Math_Score,Science_Score,English_Score,Attendance_Percentage,Passed
0,1,Aarav,15,M,78,82,75,92,True
1,2,Diya,16,F,85,88,80,95,True
2,3,Rahul,15,M,69,70,72,88,True
3,4,Sneha,17,F,90,92,85,98,True
4,5,Karan,16,M,72,75,70,85,True
5,6,Ananya,15,F,88,90,83,96,True
6,7,Rohit,17,M,65,68,74,80,False
7,8,Pooja,16,F,91,94,88,99,True
8,9,Vikram,18,M,74,77,76,90,True
9,10,Neha,15,F,86,89,82,94,True


20 rows and 9 columns

In [8]:
df.shape

(20, 9)

In [11]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Math_Score', 'Science_Score',
       'English_Score', 'Attendance_Percentage', 'Passed'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   Student_ID             20 non-null     int64 
 1   Name                   20 non-null     object
 2   Age                    20 non-null     int64 
 3   Gender                 20 non-null     object
 4   Math_Score             20 non-null     int64 
 5   Science_Score          20 non-null     int64 
 6   English_Score          20 non-null     int64 
 7   Attendance_Percentage  20 non-null     int64 
 8   Passed                 20 non-null     bool  
dtypes: bool(1), int64(6), object(2)
memory usage: 1.4+ KB


In [14]:
df.dtypes

,0
Student_ID,int64
Name,object
Age,int64
Gender,object
Math_Score,int64
Science_Score,int64
English_Score,int64
Attendance_Percentage,int64
Passed,bool


In [23]:
numerical_df=df.select_dtypes(include=["int64","float64"])
numerical_df

,Student_ID,Age,Math_Score,Science_Score,English_Score,Attendance_Percentage
0,1,15,78,82,75,92
1,2,16,85,88,80,95
2,3,15,69,70,72,88
3,4,17,90,92,85,98
4,5,16,72,75,70,85
5,6,15,88,90,83,96
6,7,17,65,68,74,80
7,8,16,91,94,88,99
8,9,18,74,77,76,90
9,10,15,86,89,82,94


In [24]:
import numpy as np

In [25]:
num_array=numerical_df.to_numpy()
num_array

array([[ 1, 15, 78, 82, 75, 92],
       [ 2, 16, 85, 88, 80, 95],
       [ 3, 15, 69, 70, 72, 88],
       [ 4, 17, 90, 92, 85, 98],
       [ 5, 16, 72, 75, 70, 85],
       [ 6, 15, 88, 90, 83, 96],
       [ 7, 17, 65, 68, 74, 80],
       [ 8, 16, 91, 94, 88, 99],
       [ 9, 18, 74, 77, 76, 90],
       [10, 15, 86, 89, 82, 94],
       [11, 16, 80, 83, 78, 93],
       [12, 17, 92, 95, 90, 97],
       [13, 15, 68, 72, 73, 86],
       [14, 16, 89, 91, 86, 96],
       [15, 18, 76, 79, 79, 91],
       [16, 17, 90, 93, 87, 98],
       [17, 16, 73, 76, 75, 89],
       [18, 15, 84, 86, 81, 92],
       [19, 17, 79, 81, 77, 90],
       [20, 16, 87, 90, 84, 95]])

In [18]:
num_array.shape

(20, 6)

Average of every column

In [19]:
np.mean(num_array,axis=0)

array([10.5 , 16.15, 80.8 , 83.55, 79.75, 92.2 ])

In [28]:
np.max(num_array, axis=0)

array([20, 18, 92, 95, 90, 99])

In [30]:
np.max(num_array)

np.int64(99)

In [29]:
np.min(num_array,axis=0)

array([ 1, 15, 65, 68, 70, 80])

In [31]:
np.min(num_array)

np.int64(1)

In [34]:
df["Math_Score"]>85

,Math_Score
0,False
1,False
2,False
3,True
4,False
5,True
6,False
7,True
8,False
9,True


In [35]:
df[df["Math_Score"]>85]

,Student_ID,Name,Age,Gender,Math_Score,Science_Score,English_Score,Attendance_Percentage,Passed
3,4,Sneha,17,F,90,92,85,98,True
5,6,Ananya,15,F,88,90,83,96,True
7,8,Pooja,16,F,91,94,88,99,True
9,10,Neha,15,F,86,89,82,94,True
11,12,Isha,17,F,92,95,90,97,True
13,14,Riya,16,F,89,91,86,96,True
15,16,Kriti,17,F,90,93,87,98,True
19,20,Priya,16,F,87,90,84,95,True


In [42]:
df[(df["Math_Score"]>80) & (df["Science_Score"]>85)]

,Student_ID,Name,Age,Gender,Math_Score,Science_Score,English_Score,Attendance_Percentage,Passed
1,2,Diya,16,F,85,88,80,95,True
3,4,Sneha,17,F,90,92,85,98,True
5,6,Ananya,15,F,88,90,83,96,True
7,8,Pooja,16,F,91,94,88,99,True
9,10,Neha,15,F,86,89,82,94,True
11,12,Isha,17,F,92,95,90,97,True
13,14,Riya,16,F,89,91,86,96,True
15,16,Kriti,17,F,90,93,87,98,True
17,18,Tanya,15,F,84,86,81,92,True
19,20,Priya,16,F,87,90,84,95,True


In [46]:
df.iloc[0:5]

,Student_ID,Name,Age,Gender,Math_Score,Science_Score,English_Score,Attendance_Percentage,Passed
0,1,Aarav,15,M,78,82,75,92,True
1,2,Diya,16,F,85,88,80,95,True
2,3,Rahul,15,M,69,70,72,88,True
3,4,Sneha,17,F,90,92,85,98,True
4,5,Karan,16,M,72,75,70,85,True


In [59]:
df.iloc[0:5, 0:4]

,Student_ID,Name,Age,Gender
0,1,Aarav,15,M
1,2,Diya,16,F
2,3,Rahul,15,M
3,4,Sneha,17,F
4,5,Karan,16,M


In [50]:
df.loc[3]

,3
Student_ID,4
Name,Sneha
Age,17
Gender,F
Math_Score,90
Science_Score,92
English_Score,85
Attendance_Percentage,98
Passed,True


In [51]:
df.iloc[3]

,3
Student_ID,4
Name,Sneha
Age,17
Gender,F
Math_Score,90
Science_Score,92
English_Score,85
Attendance_Percentage,98
Passed,True


In [52]:
df2=df.set_index("Student_ID")

In [58]:
df2.head()

,Name,Age,Gender,Math_Score,Science_Score,English_Score,Attendance_Percentage,Passed
Student_ID,,,,,,,,
1,Aarav,15,M,78,82,75,92,True
2,Diya,16,F,85,88,80,95,True
3,Rahul,15,M,69,70,72,88,True
4,Sneha,17,F,90,92,85,98,True
5,Karan,16,M,72,75,70,85,True


it goes according row position

In [55]:
df2.loc[3]

,3
Name,Rahul
Age,15
Gender,M
Math_Score,69
Science_Score,70
English_Score,72
Attendance_Percentage,88
Passed,True


It goes according to index

In [56]:
df2.iloc[3]

,4
Name,Sneha
Age,17
Gender,F
Math_Score,90
Science_Score,92
English_Score,85
Attendance_Percentage,98
Passed,True


In [61]:
df.loc[:,["Name","Math_Score","Science_Score"]]

,Name,Math_Score,Science_Score
0,Aarav,78,82
1,Diya,85,88
2,Rahul,69,70
3,Sneha,90,92
4,Karan,72,75
5,Ananya,88,90
6,Rohit,65,68
7,Pooja,91,94
8,Vikram,74,77
9,Neha,86,89


In [63]:
df["Total_Score"]=df["Math_Score"]+df["Science_Score"]+df["English_Score"]
print(df["Total_Score"])

0     235
1     253
2     211
3     267
4     217
5     261
6     207
7     273
8     227
9     257
10    241
11    277
12    213
13    266
14    234
15    270
16    224
17    251
18    237
19    261
Name: Total_Score, dtype: int64


In [65]:
df["Average_Score"]=df["Total_Score"]/3
print(df["Average_Score"])

0     78.333333
1     84.333333
2     70.333333
3     89.000000
4     72.333333
5     87.000000
6     69.000000
7     91.000000
8     75.666667
9     85.666667
10    80.333333
11    92.333333
12    71.000000
13    88.666667
14    78.000000
15    90.000000
16    74.666667
17    83.666667
18    79.000000
19    87.000000
Name: Average_Score, dtype: float64


In [67]:
df.groupby("Gender")["Average_Score"].mean()

,Average_Score
Gender,
F,87.866667
M,74.866667
